name: fynsta
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # INTERNATIONALIZATION
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2 # Updated version from your file

  # ICONS
  cupertino_icons: ^1.0.8

  # STATE MANAGEMENT
  provider: ^6.1.2

  # UI PACKAGES
  smooth_page_indicator: ^1.1.0
  pinput: ^5.0.0

  # DEVICE & SYSTEM
  audioplayers: ^6.0.0
  http: ^1.2.1
  flutter_native_splash: ^2.4.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # INTERNATIONALIZATION
  generate: true

  uses-material-design: true

  # ASSETS (Corrected Path)
  assets:
    - assets/